//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int U_ID { get; set; }
        public int S_ID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public string TypeEN { get; set; }
        public string StateEN { get; set; }
        public string TypeAR { get; set; }
        public string StateAR { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual User User { get; set; }
    }
}
