//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URL()
        {
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public string URL1 { get; set; }
        public System.DateTime Date { get; set; }
        public bool Expired { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
