//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Text;
    using System.ComponentModel.DataAnnotations;
    using Resources;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }

        public int ID { get; set; }
        [Display(Name = "Username", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "UsernameRequired",
            ErrorMessageResourceType = typeof(Resources))]
        public string Username { get; set; }
        [Display(Name = "Password", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "PasswordRequired",
            ErrorMessageResourceType = typeof(Resources))]
        [MinLength(8, ErrorMessageResourceName = "PasswordMinLength",
            ErrorMessageResourceType =typeof(Resources))]
        //[RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,20}$", ErrorMessage = "Password must contain: Minimum 8 characters at least 1 Alphabet and 1 Number")]
        public string Password { get; set; }

        [Display(Name = "Email", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "EmailRequired",
            ErrorMessageResourceType = typeof(Resources))]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name = "FirstNameEN", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "FirstNameENRequired", 
            ErrorMessageResourceType = typeof(Resources))]
        public string FirstNameEN { get; set; }
        [Display(Name = "LastNameEN", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "LastNameENRequired",
            ErrorMessageResourceType = typeof(Resources))]
        public string LastNameEN { get; set; }
        [Display(Name = "FirstNameAR", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "FirstNameARRequired",
            ErrorMessageResourceType = typeof(Resources))]
        public string FirstNameAR { get; set; }
        [Display(Name = "LastNameAR", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "LastNameARRequired",
            ErrorMessageResourceType = typeof(Resources))]
        public string LastNameAR { get; set; }
        [Display(Name = "Phone", ResourceType = typeof(Resources))]
        [MaxLength(11, ErrorMessageResourceName = "PhoneMaxLength",
            ErrorMessageResourceType =typeof(Resources))]
        public string Phone { get; set; }
        [Display(Name = "Question", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "QuestionRequired",
            ErrorMessageResourceType = typeof(Resources))]
        public int Q_ID { get; set; }
        [Display(Name = "Answer", ResourceType = typeof(Resources))]
        [RequiredAttribute(ErrorMessageResourceName = "AnswerRequired",
            ErrorMessageResourceType = typeof(Resources))]
        public string Answer { get; set; }
        public bool EmailConfirmed { get; set; }
        public decimal Wallet { get; set; }
        public bool Blocked { get; set; }
        public int LoginTrials { get; set; }
        public bool Admin { get; set; }
        public Nullable<int> URL_ID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Question Question { get; set; }
        public virtual URL URL { get; set; }


        public string MD5Hash(string text)
        {
            MD5 md5 = new MD5CryptoServiceProvider();

            //compute hash from the bytes of text  
            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(text));

            //get hash result after compute it  
            byte[] result = md5.Hash;

            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {
                //change it into 2 hexadecimal digits  
                //for each byte  
                strBuilder.Append(result[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }
    }
}