//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTW_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Text;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Orders = new HashSet<Order>();
        }

        public int ID { get; set; }

        [RequiredAttribute]
        public string Username { get; set; }

        [RequiredAttribute]
        [MinLength(8, ErrorMessage ="Password must be at least 8 characters")]
        //[RegularExpression(@"^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,20}$", ErrorMessage = "Password must contain: Minimum 8 characters at least 1 Alphabet and 1 Number")]
        public string Password { get; set; }

        [RequiredAttribute]
        [EmailAddress]
        public string Email { get; set; }

        [RequiredAttribute(ErrorMessage ="First name in English is Required")]
        public string FirstNameEN { get; set; }

        [RequiredAttribute(ErrorMessage = "Last name in English is Required")]
        public string LastNameEN { get; set; }

        [RequiredAttribute(ErrorMessage = "First name in Arabic is Required")]
        public string FirstNameAR { get; set; }

        [RequiredAttribute(ErrorMessage = "Last name in Arabic is Required")]
        public string LastNameAR { get; set; }

        [MaxLength(11, ErrorMessage ="Phone must be 11 numbers")]
        public string Phone { get; set; }

        public int Q_ID { get; set; }
        [RequiredAttribute]
        public string Answer { get; set; }
        public bool EmailConfirmed { get; set; }
        public decimal Wallet { get; set; }
        public bool Blocked { get; set; }
        public int LoginTrials { get; set; }
        public bool Admin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Question Question { get; set; }


        public string MD5Hash(string text)
        {
            MD5 md5 = new MD5CryptoServiceProvider();

            //compute hash from the bytes of text  
            md5.ComputeHash(ASCIIEncoding.ASCII.GetBytes(text));

            //get hash result after compute it  
            byte[] result = md5.Hash;

            StringBuilder strBuilder = new StringBuilder();
            for (int i = 0; i < result.Length; i++)
            {
                //change it into 2 hexadecimal digits  
                //for each byte  
                strBuilder.Append(result[i].ToString("x2"));
            }

            return strBuilder.ToString();
        }
    }
}
